clone:
        image: hg
        path: bitbucket.org/faide/py3o.template

build:
        image: xcgd/dronebase
        commands:
                - pip install setuptools --upgrade
                - python setup.py install
                - pip install tox
                - tox

notify:
  slack:
    webhook_url: $$mattermost_token
    channel: Dev
    username: drone
