clone:
        image: hg
        path: bitbucket.org/faide/py3o.template

build:
        image: xcgd/dronebase
        commands:
                - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq subversion python3-dev
                - pip install setuptools --upgrade
                # - python setup.py install # do not install to avoid having wrong version of genshi
                - pip install tox
                - tox

notify:
  slack:
    webhook_url: $$mattermost_token
    channel: Dev
    username: drone
